DROP TABLE IF EXISTS notices;

CREATE TABLE `notices` (
  `id` INTEGER UNSIGNED AUTO_INCREMENT,
  `content` TEXT NOT NULL COMMENT 'お知らせ内容',
  `published_at` DATETIME NOT NULL COMMENT '公開日時',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`)
);
