CREATE TABLE `admins` (
  `id` INTEGER UNSIGNED AUTO_INCREMENT,
  `role_id` INTEGER UNSIGNED NOT NULL,
  `firebase_uid` VARCHAR(130) UNIQUE NOT NULL COMMENT 'firebase user id',
  `email` VARCHAR(255) UNIQUE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `affiliation` VARCHAR(255) DEFAULT null COMMENT '所属（自由記述）',
  `is_disabled` BOOLEAN NOT NULL DEFAULT false COMMENT '無効状態かどうか',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`)
);
