// Code generated by goctl. DO NOT EDIT!

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	personalityDiagnoseChoicesFieldNames          = builder.RawFieldNames(&PersonalityDiagnoseChoices{})
	personalityDiagnoseChoicesRows                = strings.Join(personalityDiagnoseChoicesFieldNames, ",")
	personalityDiagnoseChoicesRowsExpectAutoSet   = strings.Join(stringx.Remove(personalityDiagnoseChoicesFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	personalityDiagnoseChoicesRowsWithPlaceHolder = strings.Join(stringx.Remove(personalityDiagnoseChoicesFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cachePersonalityDiagnoseChoicesIdPrefix   = "cache:personalityDiagnoseChoices:id:"
	cachePersonalityDiagnoseChoicesNamePrefix = "cache:personalityDiagnoseChoices:name:"
)

type (
	personalityDiagnoseChoicesModel interface {
		Insert(ctx context.Context, data *PersonalityDiagnoseChoices) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*PersonalityDiagnoseChoices, error)
		FindOneByName(ctx context.Context, name string) (*PersonalityDiagnoseChoices, error)
		Update(ctx context.Context, data *PersonalityDiagnoseChoices) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPersonalityDiagnoseChoicesModel struct {
		sqlc.CachedConn
		table string
	}

	PersonalityDiagnoseChoices struct {
		Id        uint64    `db:"id"`
		Name      string    `db:"name"`   // 選択肢名（例：そう思う、どちらでもない）
		Weight    uint64    `db:"weight"` // 回答の重み
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newPersonalityDiagnoseChoicesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPersonalityDiagnoseChoicesModel {
	return &defaultPersonalityDiagnoseChoicesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`personality_diagnose_choices`",
	}
}

func (m *defaultPersonalityDiagnoseChoicesModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	personalityDiagnoseChoicesIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesIdPrefix, id)
	personalityDiagnoseChoicesNameKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, personalityDiagnoseChoicesIdKey, personalityDiagnoseChoicesNameKey)
	return err
}

func (m *defaultPersonalityDiagnoseChoicesModel) FindOne(ctx context.Context, id uint64) (*PersonalityDiagnoseChoices, error) {
	personalityDiagnoseChoicesIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesIdPrefix, id)
	var resp PersonalityDiagnoseChoices
	err := m.QueryRowCtx(ctx, &resp, personalityDiagnoseChoicesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", personalityDiagnoseChoicesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPersonalityDiagnoseChoicesModel) FindOneByName(ctx context.Context, name string) (*PersonalityDiagnoseChoices, error) {
	personalityDiagnoseChoicesNameKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesNamePrefix, name)
	var resp PersonalityDiagnoseChoices
	err := m.QueryRowIndexCtx(ctx, &resp, personalityDiagnoseChoicesNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", personalityDiagnoseChoicesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPersonalityDiagnoseChoicesModel) Insert(ctx context.Context, data *PersonalityDiagnoseChoices) (sql.Result, error) {
	personalityDiagnoseChoicesIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesIdPrefix, data.Id)
	personalityDiagnoseChoicesNameKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, personalityDiagnoseChoicesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Weight, data.CreatedAt, data.UpdatedAt)
	}, personalityDiagnoseChoicesIdKey, personalityDiagnoseChoicesNameKey)
	return ret, err
}

func (m *defaultPersonalityDiagnoseChoicesModel) Update(ctx context.Context, newData *PersonalityDiagnoseChoices) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	personalityDiagnoseChoicesIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesIdPrefix, data.Id)
	personalityDiagnoseChoicesNameKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, personalityDiagnoseChoicesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Weight, newData.CreatedAt, newData.UpdatedAt, newData.Id)
	}, personalityDiagnoseChoicesIdKey, personalityDiagnoseChoicesNameKey)
	return err
}

func (m *defaultPersonalityDiagnoseChoicesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePersonalityDiagnoseChoicesIdPrefix, primary)
}

func (m *defaultPersonalityDiagnoseChoicesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", personalityDiagnoseChoicesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPersonalityDiagnoseChoicesModel) tableName() string {
	return m.table
}
