// Code generated by goctl. DO NOT EDIT!

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	personalityDiagnoseAnswersFieldNames          = builder.RawFieldNames(&PersonalityDiagnoseAnswers{})
	personalityDiagnoseAnswersRows                = strings.Join(personalityDiagnoseAnswersFieldNames, ",")
	personalityDiagnoseAnswersRowsExpectAutoSet   = strings.Join(stringx.Remove(personalityDiagnoseAnswersFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	personalityDiagnoseAnswersRowsWithPlaceHolder = strings.Join(stringx.Remove(personalityDiagnoseAnswersFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cachePersonalityDiagnoseAnswersIdPrefix                      = "cache:personalityDiagnoseAnswers:id:"
	cachePersonalityDiagnoseAnswersAnswerGroupIdQuestionIdPrefix = "cache:personalityDiagnoseAnswers:answerGroupId:questionId:"
)

type (
	personalityDiagnoseAnswersModel interface {
		Insert(ctx context.Context, data *PersonalityDiagnoseAnswers) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*PersonalityDiagnoseAnswers, error)
		FindOneByAnswerGroupIdQuestionId(ctx context.Context, answerGroupId string, questionId uint64) (*PersonalityDiagnoseAnswers, error)
		Update(ctx context.Context, data *PersonalityDiagnoseAnswers) error
		Delete(ctx context.Context, id string) error
	}

	defaultPersonalityDiagnoseAnswersModel struct {
		sqlc.CachedConn
		table string
	}

	PersonalityDiagnoseAnswers struct {
		Id            string    `db:"id"`              // ULID
		AnswerGroupId string    `db:"answer_group_id"` // ULID 回答グループごとに作成
		QuestionId    uint64    `db:"question_id"`     // 設問ID
		ChoiceId      uint64    `db:"choice_id"`       // 選択した選択肢のID
		UserId        string    `db:"user_id"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newPersonalityDiagnoseAnswersModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultPersonalityDiagnoseAnswersModel {
	return &defaultPersonalityDiagnoseAnswersModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`personality_diagnose_answers`",
	}
}

func (m *defaultPersonalityDiagnoseAnswersModel) Delete(ctx context.Context, id string) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cachePersonalityDiagnoseAnswersAnswerGroupIdQuestionIdPrefix, data.AnswerGroupId, data.QuestionId)
	personalityDiagnoseAnswersIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseAnswersIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey, personalityDiagnoseAnswersIdKey)
	return err
}

func (m *defaultPersonalityDiagnoseAnswersModel) FindOne(ctx context.Context, id string) (*PersonalityDiagnoseAnswers, error) {
	personalityDiagnoseAnswersIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseAnswersIdPrefix, id)
	var resp PersonalityDiagnoseAnswers
	err := m.QueryRowCtx(ctx, &resp, personalityDiagnoseAnswersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", personalityDiagnoseAnswersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPersonalityDiagnoseAnswersModel) FindOneByAnswerGroupIdQuestionId(ctx context.Context, answerGroupId string, questionId uint64) (*PersonalityDiagnoseAnswers, error) {
	personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cachePersonalityDiagnoseAnswersAnswerGroupIdQuestionIdPrefix, answerGroupId, questionId)
	var resp PersonalityDiagnoseAnswers
	err := m.QueryRowIndexCtx(ctx, &resp, personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `answer_group_id` = ? and `question_id` = ? limit 1", personalityDiagnoseAnswersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, answerGroupId, questionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPersonalityDiagnoseAnswersModel) Insert(ctx context.Context, data *PersonalityDiagnoseAnswers) (sql.Result, error) {
	personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cachePersonalityDiagnoseAnswersAnswerGroupIdQuestionIdPrefix, data.AnswerGroupId, data.QuestionId)
	personalityDiagnoseAnswersIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseAnswersIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, personalityDiagnoseAnswersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.AnswerGroupId, data.QuestionId, data.ChoiceId, data.UserId, data.CreatedAt, data.UpdatedAt)
	}, personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey, personalityDiagnoseAnswersIdKey)
	return ret, err
}

func (m *defaultPersonalityDiagnoseAnswersModel) Update(ctx context.Context, newData *PersonalityDiagnoseAnswers) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cachePersonalityDiagnoseAnswersAnswerGroupIdQuestionIdPrefix, data.AnswerGroupId, data.QuestionId)
	personalityDiagnoseAnswersIdKey := fmt.Sprintf("%s%v", cachePersonalityDiagnoseAnswersIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, personalityDiagnoseAnswersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AnswerGroupId, newData.QuestionId, newData.ChoiceId, newData.UserId, newData.CreatedAt, newData.UpdatedAt, newData.Id)
	}, personalityDiagnoseAnswersAnswerGroupIdQuestionIdKey, personalityDiagnoseAnswersIdKey)
	return err
}

func (m *defaultPersonalityDiagnoseAnswersModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePersonalityDiagnoseAnswersIdPrefix, primary)
}

func (m *defaultPersonalityDiagnoseAnswersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", personalityDiagnoseAnswersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPersonalityDiagnoseAnswersModel) tableName() string {
	return m.table
}
