// Code generated by goctl. DO NOT EDIT!

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	serviceTriggersFieldNames          = builder.RawFieldNames(&ServiceTriggers{})
	serviceTriggersRows                = strings.Join(serviceTriggersFieldNames, ",")
	serviceTriggersRowsExpectAutoSet   = strings.Join(stringx.Remove(serviceTriggersFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	serviceTriggersRowsWithPlaceHolder = strings.Join(stringx.Remove(serviceTriggersFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheServiceTriggersIdPrefix   = "cache:serviceTriggers:id:"
	cacheServiceTriggersNamePrefix = "cache:serviceTriggers:name:"
)

type (
	serviceTriggersModel interface {
		Insert(ctx context.Context, data *ServiceTriggers) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ServiceTriggers, error)
		FindOneByName(ctx context.Context, name string) (*ServiceTriggers, error)
		Update(ctx context.Context, data *ServiceTriggers) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultServiceTriggersModel struct {
		sqlc.CachedConn
		table string
	}

	ServiceTriggers struct {
		Id   uint64 `db:"id"`
		Name string `db:"name"` // 例：インスタグラム、その他
	}
)

func newServiceTriggersModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultServiceTriggersModel {
	return &defaultServiceTriggersModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`service_triggers`",
	}
}

func (m *defaultServiceTriggersModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	serviceTriggersIdKey := fmt.Sprintf("%s%v", cacheServiceTriggersIdPrefix, id)
	serviceTriggersNameKey := fmt.Sprintf("%s%v", cacheServiceTriggersNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, serviceTriggersIdKey, serviceTriggersNameKey)
	return err
}

func (m *defaultServiceTriggersModel) FindOne(ctx context.Context, id uint64) (*ServiceTriggers, error) {
	serviceTriggersIdKey := fmt.Sprintf("%s%v", cacheServiceTriggersIdPrefix, id)
	var resp ServiceTriggers
	err := m.QueryRowCtx(ctx, &resp, serviceTriggersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", serviceTriggersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultServiceTriggersModel) FindOneByName(ctx context.Context, name string) (*ServiceTriggers, error) {
	serviceTriggersNameKey := fmt.Sprintf("%s%v", cacheServiceTriggersNamePrefix, name)
	var resp ServiceTriggers
	err := m.QueryRowIndexCtx(ctx, &resp, serviceTriggersNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", serviceTriggersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultServiceTriggersModel) Insert(ctx context.Context, data *ServiceTriggers) (sql.Result, error) {
	serviceTriggersIdKey := fmt.Sprintf("%s%v", cacheServiceTriggersIdPrefix, data.Id)
	serviceTriggersNameKey := fmt.Sprintf("%s%v", cacheServiceTriggersNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, serviceTriggersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, serviceTriggersIdKey, serviceTriggersNameKey)
	return ret, err
}

func (m *defaultServiceTriggersModel) Update(ctx context.Context, newData *ServiceTriggers) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	serviceTriggersIdKey := fmt.Sprintf("%s%v", cacheServiceTriggersIdPrefix, data.Id)
	serviceTriggersNameKey := fmt.Sprintf("%s%v", cacheServiceTriggersNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, serviceTriggersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Id)
	}, serviceTriggersIdKey, serviceTriggersNameKey)
	return err
}

func (m *defaultServiceTriggersModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheServiceTriggersIdPrefix, primary)
}

func (m *defaultServiceTriggersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", serviceTriggersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultServiceTriggersModel) tableName() string {
	return m.table
}
