// Code generated by goctl. DO NOT EDIT!

package repository

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAddressesFieldNames          = builder.RawFieldNames(&UserAddresses{})
	userAddressesRows                = strings.Join(userAddressesFieldNames, ",")
	userAddressesRowsExpectAutoSet   = strings.Join(stringx.Remove(userAddressesFieldNames, "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userAddressesRowsWithPlaceHolder = strings.Join(stringx.Remove(userAddressesFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserAddressesIdPrefix     = "cache:userAddresses:id:"
	cacheUserAddressesUserIdPrefix = "cache:userAddresses:userId:"
)

type (
	userAddressesModel interface {
		Insert(ctx context.Context, data *UserAddresses) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UserAddresses, error)
		FindOneByUserId(ctx context.Context, userId string) (*UserAddresses, error)
		Update(ctx context.Context, data *UserAddresses) error
		Delete(ctx context.Context, id string) error
	}

	defaultUserAddressesModel struct {
		sqlc.CachedConn
		table string
	}

	UserAddresses struct {
		Id         string `db:"id"` // ULID
		UserId     string `db:"user_id"`
		PostalCode string `db:"postal_code"` // 郵便番号
		Address    string `db:"address"`     // 住所
	}
)

func newUserAddressesModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserAddressesModel {
	return &defaultUserAddressesModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_addresses`",
	}
}

func (m *defaultUserAddressesModel) Delete(ctx context.Context, id string) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, id)
	userAddressesUserIdKey := fmt.Sprintf("%s%v", cacheUserAddressesUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userAddressesIdKey, userAddressesUserIdKey)
	return err
}

func (m *defaultUserAddressesModel) FindOne(ctx context.Context, id string) (*UserAddresses, error) {
	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, id)
	var resp UserAddresses
	err := m.QueryRowCtx(ctx, &resp, userAddressesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressesModel) FindOneByUserId(ctx context.Context, userId string) (*UserAddresses, error) {
	userAddressesUserIdKey := fmt.Sprintf("%s%v", cacheUserAddressesUserIdPrefix, userId)
	var resp UserAddresses
	err := m.QueryRowIndexCtx(ctx, &resp, userAddressesUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userAddressesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAddressesModel) Insert(ctx context.Context, data *UserAddresses) (sql.Result, error) {
	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, data.Id)
	userAddressesUserIdKey := fmt.Sprintf("%s%v", cacheUserAddressesUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userAddressesRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserId, data.PostalCode, data.Address)
	}, userAddressesIdKey, userAddressesUserIdKey)
	return ret, err
}

func (m *defaultUserAddressesModel) Update(ctx context.Context, newData *UserAddresses) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userAddressesIdKey := fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, data.Id)
	userAddressesUserIdKey := fmt.Sprintf("%s%v", cacheUserAddressesUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAddressesRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.PostalCode, newData.Address, newData.Id)
	}, userAddressesIdKey, userAddressesUserIdKey)
	return err
}

func (m *defaultUserAddressesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserAddressesIdPrefix, primary)
}

func (m *defaultUserAddressesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAddressesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserAddressesModel) tableName() string {
	return m.table
}
